config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("tat.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("tasks/", include("tat.tasks.urls", namespace="tasks")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

tat/tasks/urls.py
from django.urls import include, path, re_path
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token

from . import views
from .api import views as api_views

api_router = routers.DefaultRouter()
api_router.register(
    r"classification_tasks",
    api_views.ClassificationTaskViewSet,
    basename="classification_task",
)
api_router.register(
    r"classification_task_groups",
    api_views.ClassificationTaskGroupViewSet,
    basename="classification_task_group",
)
api_router.register(
    r"html_documents", api_views.HTMLDocumentViewSet, basename="html_document"
)
api_router.register(r"html_tables", api_views.HTMLTableViewSet, basename="html_table")

app_name = "tasks"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path(
        "classification/",
        views.ClassificationTaskGroupListView.as_view(),
        name="classification_tasks",
    ),
    re_path(
        r"classification/edit_task_group/(?P<pk>\d+)/$",
        views.ClassificationTaskGroupEditView.as_view(),
        name="classification_group_edit",
    ),
    re_path(
        r"classification/delete_task_group/(?P<pk>\d+)/$",
        views.ClassificationTaskGroupDeleteView.as_view(),
        name="classification_group_delete",
    ),
    re_path(
        r"classification/delete_task/(?P<pk>\d+)/$",
        views.ClassificationTaskDeleteView.as_view(),
        name="classification_task_delete",
    ),
    re_path(
        r"classification/annotate/(?P<pk>\d+)/$",
        views.ClassificationTaskAnnotateFormView.as_view(),
        name="classification_task_annotate",
    ),
    path(
        r"html_table_context/<int:pk>/",
        views.HTMLTableContextView.as_view(),
        name="html_table_context",
    ),
    path("api/", include(api_router.urls)),
    path(
        "api/html_document_retrieve_source_url/<path:source_url>",
        api_views.HTMLDocumentRetrieveSourceUrl.as_view(),
        name="html_document_retrieve_source_url",
    ),
    path(
        "api/classification_task_group_retrieve_name/<str:name>",
        api_views.ClassificatonTaskGroupRetrieveName.as_view(),
        name="classification_task_group_retrieve_name",
    ),
    path(
        "api/html_table_retrieve_source_url_xpath/",
        api_views.html_table_retrieve_source_url_xpath,
        name="html_table_retrieve_source_url_xpath",
    ),
    path(
        "download_all_data",
        views.download_all_data,
        name="download_all_data",
    ),
    path(
        "classification_group_download/<int:pk>",
        views.classification_group_download,
        name="classification_group_download",
    ),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("auth-token/", obtain_auth_token),
]

tat/users/urls.py
from django.urls import path

from tat.users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

tat/tasks/api/models.py
# Create your models here.

tat/tasks/models.py
import uuid as uuid_lib

from django.conf import settings
from django.contrib.postgres.fields import ArrayField
from django.db import models


class HTMLDocument(models.Model):
    html = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    source_url = models.URLField(unique=True)
    uuid = models.UUIDField(
        db_index=True, default=uuid_lib.uuid4, editable=False, unique=True
    )


class HTMLTable(models.Model):
    source_document = models.ForeignKey(
        HTMLDocument,
        on_delete=models.CASCADE,
        related_name="html_tables",
        to_field="uuid",
    )
    xpath = models.CharField(
        max_length=256
    )  # where in the source document the classification task is from
    uuid = models.UUIDField(
        db_index=True, default=uuid_lib.uuid4, editable=False, unique=True
    )

    class Meta:
        unique_together = ("xpath", "source_document")


class ClassificationTaskGroup(models.Model):
    name = models.CharField(max_length=256, unique=True)
    table_class_options = ArrayField(models.CharField(max_length=256))
    uuid = models.UUIDField(
        db_index=True, default=uuid_lib.uuid4, editable=False, unique=True
    )

    def completed_task_count(self):
        return self.tasks.filter(completed=True).count()


class ClassificationTask(models.Model):
    name = models.CharField(max_length=256)
    uuid = models.UUIDField(
        db_index=True, default=uuid_lib.uuid4, editable=False, unique=True
    )
    table_class = models.CharField(max_length=256, blank=True)
    completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    completed_at = models.DateTimeField(null=True)  # Create your models here.
    completed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True,
        related_name="classification_tasks",
    )
    html_table = models.ForeignKey(
        HTMLTable,
        on_delete=models.CASCADE,
        related_name="classification_tasks",
        to_field="uuid",
    )
    group = models.ForeignKey(
        ClassificationTaskGroup,
        on_delete=models.CASCADE,
        related_name="tasks",
        to_field="uuid",
    )

    class Meta:
        unique_together = ("html_table", "group")

tat/users/models.py
import django.db.models as models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models import CharField, IntegerField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for tat."""

    class Types(models.TextChoices):
        NORMAL = "NORMAL", "Normal"
        ADMIN = "ADMIN", "Admin"

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore
    type = models.CharField(
        _("Type"), max_length=64, choices=Types.choices, default=Types.NORMAL
    )
    html_table_context_before = IntegerField(
        default=10, validators=[MaxValueValidator(100), MinValueValidator(0)]
    )
    html_table_context_after = IntegerField(
        default=0, validators=[MaxValueValidator(100), MinValueValidator(0)]
    )

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

tat/tasks/forms.py
from django import forms


class ClassificationTaskAnnotateForm(forms.Form):
    def __init__(self, *args, **kwargs):
        table_class_options = kwargs.pop("table_class_options")
        super().__init__(*args, **kwargs)
        self.fields["table_class"] = forms.ChoiceField(
            choices=[(s, s) for s in table_class_options],
            widget=forms.RadioSelect,
        )


class ClassificationTaskContextForm(forms.Form):
    before = forms.IntegerField(min_value=0, max_value=100)
    after = forms.IntegerField(min_value=0, max_value=100)

tat/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

tat/tasks/api/views.py
import urllib.parse

from django.shortcuts import get_object_or_404
from rest_framework import generics, permissions, status, viewsets
from rest_framework.decorators import api_view
from rest_framework.response import Response

from ..models import (
    ClassificationTask,
    ClassificationTaskGroup,
    HTMLDocument,
    HTMLTable,
)
from .serializers import (
    ClassificationTaskGroupSerializer,
    ClassificationTaskSerializer,
    HTMLDocumentSerializer,
    HTMLTableSerializer,
)


class HTMLDocumentViewSet(viewsets.ModelViewSet):
    queryset = HTMLDocument.objects.all()
    serializer_class = HTMLDocumentSerializer
    permission_classes = (permissions.IsAuthenticated,)
    lookup_field = "uuid"


class HTMLDocumentRetrieveSourceUrl(generics.RetrieveAPIView):
    queryset = HTMLDocument.objects.all()
    serializer_class = HTMLDocumentSerializer
    permission_classes = (permissions.IsAuthenticated,)
    # lookup_url_kwarg = "source_url"
    lookup_field = "source_url"

    def get_object(self):
        """
        Returns the object the view is displaying.

        You may want to override this if you need to provide non-standard
        queryset lookups.  Eg if objects are referenced using multiple
        keyword arguments in the url conf.
        """
        queryset = self.filter_queryset(self.get_queryset())

        # Perform the lookup filtering.
        lookup_url_kwarg = self.lookup_url_kwarg or self.lookup_field

        assert lookup_url_kwarg in self.kwargs, (
            "Expected view %s to be called with a URL keyword argument "
            'named "%s". Fix your URL conf, or set the `.lookup_field` '
            "attribute on the view correctly."
            % (self.__class__.__name__, lookup_url_kwarg)
        )

        filter_kwargs = {
            self.lookup_field: urllib.parse.unquote(self.kwargs[lookup_url_kwarg])
        }
        obj = get_object_or_404(queryset, **filter_kwargs)

        # May raise a permission denied
        self.check_object_permissions(self.request, obj)

        return obj


class HTMLTableViewSet(viewsets.ModelViewSet):
    queryset = HTMLTable.objects.all()
    serializer_class = HTMLTableSerializer
    permission_classes = (permissions.IsAuthenticated,)
    lookup_field = "uuid"


@api_view(["GET"])
def html_table_retrieve_source_url_xpath(request):
    data = {
        "source_document": request.data.get("source_document"),
        "xpath": request.data.get("xpath"),
    }
    for k, v in data.items():
        if v is None:
            return Response(
                {"Must not be null": [k]}, status=status.HTTP_400_BAD_REQUEST
            )

    try:
        html_table = HTMLTable.objects.get(**data)
    except HTMLTable.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
    if request.method == "GET":
        serializer = HTMLTableSerializer(html_table, many=False)
        return Response(serializer.data)


class ClassificationTaskViewSet(viewsets.ModelViewSet):
    queryset = ClassificationTask.objects.all()
    serializer_class = ClassificationTaskSerializer
    permission_classes = (permissions.IsAuthenticated,)
    lookup_field = "uuid"


class ClassificationTaskGroupViewSet(viewsets.ModelViewSet):
    queryset = ClassificationTaskGroup.objects.all()
    serializer_class = ClassificationTaskGroupSerializer
    permission_classes = (permissions.IsAuthenticated,)
    lookup_field = "uuid"


class ClassificatonTaskGroupRetrieveName(generics.RetrieveAPIView):
    queryset = ClassificationTaskGroup.objects.all()
    serializer_class = ClassificationTaskGroupSerializer
    permission_classes = (permissions.IsAuthenticated,)
    lookup_field = "name"

    def get_object(self):
        """
        Returns the object the view is displaying.

        You may want to override this if you need to provide non-standard
        queryset lookups.  Eg if objects are referenced using multiple
        keyword arguments in the url conf.
        """
        queryset = self.filter_queryset(self.get_queryset())

        # Perform the lookup filtering.
        lookup_url_kwarg = self.lookup_url_kwarg or self.lookup_field

        assert lookup_url_kwarg in self.kwargs, (
            "Expected view %s to be called with a URL keyword argument "
            'named "%s". Fix your URL conf, or set the `.lookup_field` '
            "attribute on the view correctly."
            % (self.__class__.__name__, lookup_url_kwarg)
        )

        filter_kwargs = {
            self.lookup_field: urllib.parse.unquote_plus(self.kwargs[lookup_url_kwarg])
        }
        obj = get_object_or_404(queryset, **filter_kwargs)

        # May raise a permission denied
        self.check_object_permissions(self.request, obj)

        return obj

tat/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

tat/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

tat/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}TAT{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Annotate HTML tables">
    <meta name="author" content="Dave Fol">

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Barlow:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Merriweather+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&display=swap" rel="stylesheet">

    {% block css %}
    <!-- Your stuff: Third-party CSS libraries go here -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">

    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endblock %}
    <!-- Le javascript
      ================================================== -->
      {# Placed at the top of the document so pages load faster with defer #}
      {% block javascript %}
      <!-- Bootstrap JS -->
      <script defer src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.1/js/bootstrap.min.js" integrity="sha512-ewfXo9Gq53e1q1+WDTjaHAGZ8UvCWq0eXONhwDuIoaH8xz2r96uoAYaQCm1oQhnBfRXrvJztNXFsTloJfgbL5Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
      <!-- Your stuff: Third-party javascript libraries go here -->
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>

      <!-- place project specific Javascript in this file -->
      <script defer src="{% static 'js/project.js' %}"></script>

      {% endblock javascript %}

  </head>

  <body>
    <nav class="navbar has-shadow is-spaced">
      <div class="navbar-brand">
        <!-- logo, tagline, nacbar-burger -->
        <a class="navbar-item" href="{% url 'home' %}"><img class="mr-2" src="{% static 'images/tabbage_monograph_logo.svg' %}"></img>TAT</a>
        <div class="navbar-burger">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <div class="navbar-menu">
        <!-- User name, dropdown menu -->
        <div class="navbar-start">
          <a class="navbar-item" href="{% url 'about' %}">About</a>
        </div>

        <div class="navbar-end">
          {% if request.user.is_authenticated %}
          <a class="navbar-item" href="{% url 'tasks:index' %}">Tasks</a>

          <a class="navbar-item" href="{% url 'users:detail' request.user.username  %}">{% translate "My Profile" %}</a>
          <a class="navbar-item" href="{% url 'account_logout' %}">{% translate "Sign Out" %}</a>
          {% else %}
          <a class="navbar-item" href="{% url 'account_signup' %}">{% translate "Sign Up" %}</a>
          <a class="navbar-item" href="{% url 'account_login' %}">{% translate "Sign In" %}</a>
          {% endif %}
        </div>
      </div>
    </nav>


    {% if messages %}
    {% for message in messages %}
    <div class="mb-0 alert message {% if message.tags %}alert-{{ message.tags }}{% endif %}">
      <div class="message-header">
        {{ message }}
        <button type="button" class="delete" data-dismiss="alert" aria-label="Close" onclick="$(this).parent().parent().alert('close')"></button>
      </div>
    </div>
    {% endfor %}
    {% endif %}

    {% block content %}
    {% endblock content %}


    {% block modal %}{% endblock modal %}

    {% block inline_javascript %}
    <script>
      window.addEventListener('DOMContentLoaded', () => {
            });
    </script>
    {% endblock inline_javascript %}
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
  </body>
</html>

tat/templates/centered_hero.html
{% extends "base.html" %}
{% block title %}{% block head_title %}{% endblock head_title %}{% endblock title %}

{% block content %}
<section class="hero is-primary is-fullheight-with-navbar">
  <div class="hero-body">
    <div class="container">
      <div class="columns is-centered">
        <div class="column is-5">
    {% block inner %}{% endblock %}
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

tat/templates/centered_hero_wide.html
{% extends "base.html" %}
{% block title %}{% block head_title %}{% endblock head_title %}{% endblock title %}

{% block content %}
<section class="hero is-primary is-fullheight-with-navbar">
  <div class="hero-body">
    <div class="container">
      <div class="columns is-centered">
        <div class="column is-three-quarters">
    {% block inner %}{% endblock %}
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}