config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("tat.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("tasks/", include("tat.tasks.urls", namespace="tasks")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

tat/tasks/urls.py
from django.urls import include, path, re_path
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token

from . import views
from .api import views as api_views

api_router = routers.DefaultRouter()
api_router.register(
    r"classification_tasks",
    api_views.ClassificationTaskViewSet,
    basename="classification_task",
)
api_router.register(
    r"classification_task_groups",
    api_views.ClassificationTaskGroupViewSet,
    basename="classification_task_group",
)
api_router.register(
    r"html_documents", api_views.HTMLDocumentViewSet, basename="html_document"
)
api_router.register(r"html_tables", api_views.HTMLTableViewSet, basename="html_table")

app_name = "tasks"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path(
        "classification/",
        views.ClassificationTaskGroupListView.as_view(),
        name="classification_tasks",
    ),
    re_path(
        r"classification/edit_task_group/(?P<pk>\d+)/$",
        views.ClassificationTaskGroupEditView.as_view(),
        name="classification_group_edit",
    ),
    re_path(
        r"classification/delete_task_group/(?P<pk>\d+)/$",
        views.ClassificationTaskGroupDeleteView.as_view(),
        name="classification_group_delete",
    ),
    re_path(
        r"classification/delete_task/(?P<pk>\d+)/$",
        views.ClassificationTaskDeleteView.as_view(),
        name="classification_task_delete",
    ),
    re_path(
        r"classification/annotate/(?P<pk>\d+)/$",
        views.ClassificationTaskAnnotateFormView.as_view(),
        name="classification_task_annotate",
    ),
    path(
        r"html_table_context/<int:pk>/",
        views.HTMLTableContextView.as_view(),
        name="html_table_context",
    ),
    path("api/", include(api_router.urls)),
    path(
        "api/html_document_retrieve_source_url/<path:source_url>",
        api_views.HTMLDocumentRetrieveSourceUrl.as_view(),
        name="html_document_retrieve_source_url",
    ),
    path(
        "api/classification_task_group_retrieve_name/<str:name>",
        api_views.ClassificatonTaskGroupRetrieveName.as_view(),
        name="classification_task_group_retrieve_name",
    ),
    path(
        "api/html_table_retrieve_source_url_xpath/",
        api_views.html_table_retrieve_source_url_xpath,
        name="html_table_retrieve_source_url_xpath",
    ),
    path(
        "download_all_data",
        views.download_all_data,
        name="download_all_data",
    ),
    path(
        "classification_group_download/<int:pk>",
        views.classification_group_download,
        name="classification_group_download",
    ),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("auth-token/", obtain_auth_token),
]

tat/users/urls.py
from django.urls import path

from tat.users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

tat/tasks/api/models.py
# Create your models here.

tat/tasks/models.py
import uuid as uuid_lib

from django.conf import settings
from django.contrib.postgres.fields import ArrayField
from django.db import models


class HTMLDocument(models.Model):
    html = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    source_url = models.URLField(unique=True)
    uuid = models.UUIDField(
        db_index=True, default=uuid_lib.uuid4, editable=False, unique=True
    )


class HTMLTable(models.Model):
    source_document = models.ForeignKey(
        HTMLDocument,
        on_delete=models.CASCADE,
        related_name="html_tables",
        to_field="uuid",
    )
    xpath = models.CharField(
        max_length=256
    )  # where in the source document the classification task is from
    uuid = models.UUIDField(
        db_index=True, default=uuid_lib.uuid4, editable=False, unique=True
    )

    class Meta:
        unique_together = ("xpath", "source_document")


class ClassificationTaskGroup(models.Model):
    name = models.CharField(max_length=256, unique=True)
    table_class_options = ArrayField(models.CharField(max_length=256))
    uuid = models.UUIDField(
        db_index=True, default=uuid_lib.uuid4, editable=False, unique=True
    )

    def completed_task_count(self):
        return self.tasks.filter(completed=True).count()


class ClassificationTask(models.Model):
    name = models.CharField(max_length=256)
    uuid = models.UUIDField(
        db_index=True, default=uuid_lib.uuid4, editable=False, unique=True
    )
    table_class = models.CharField(max_length=256, blank=True)
    completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    completed_at = models.DateTimeField(null=True)  # Create your models here.
    completed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True,
        related_name="classification_tasks",
    )
    html_table = models.ForeignKey(
        HTMLTable,
        on_delete=models.CASCADE,
        related_name="classification_tasks",
        to_field="uuid",
    )
    group = models.ForeignKey(
        ClassificationTaskGroup,
        on_delete=models.CASCADE,
        related_name="tasks",
        to_field="uuid",
    )

    class Meta:
        unique_together = ("html_table", "group")

tat/users/models.py
import django.db.models as models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models import CharField, IntegerField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for tat."""

    class Types(models.TextChoices):
        NORMAL = "NORMAL", "Normal"
        ADMIN = "ADMIN", "Admin"

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore
    type = models.CharField(
        _("Type"), max_length=64, choices=Types.choices, default=Types.NORMAL
    )
    html_table_context_before = IntegerField(
        default=10, validators=[MaxValueValidator(100), MinValueValidator(0)]
    )
    html_table_context_after = IntegerField(
        default=0, validators=[MaxValueValidator(100), MinValueValidator(0)]
    )

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

tat/tasks/forms.py
from django import forms


class ClassificationTaskAnnotateForm(forms.Form):
    def __init__(self, *args, **kwargs):
        table_class_options = kwargs.pop("table_class_options")
        super().__init__(*args, **kwargs)
        self.fields["table_class"] = forms.ChoiceField(
            choices=[(s, s) for s in table_class_options],
            widget=forms.RadioSelect,
        )


class ClassificationTaskContextForm(forms.Form):
    before = forms.IntegerField(min_value=0, max_value=100)
    after = forms.IntegerField(min_value=0, max_value=100)

tat/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

tat/tasks/api/views.py
import urllib.parse

from django.shortcuts import get_object_or_404
from rest_framework import generics, permissions, status, viewsets
from rest_framework.decorators import api_view
from rest_framework.response import Response

from ..models import (
    ClassificationTask,
    ClassificationTaskGroup,
    HTMLDocument,
    HTMLTable,
)
from .serializers import (
    ClassificationTaskGroupSerializer,
    ClassificationTaskSerializer,
    HTMLDocumentSerializer,
    HTMLTableSerializer,
)


class HTMLDocumentViewSet(viewsets.ModelViewSet):
    queryset = HTMLDocument.objects.all()
    serializer_class = HTMLDocumentSerializer
    permission_classes = (permissions.IsAuthenticated,)
    lookup_field = "uuid"


class HTMLDocumentRetrieveSourceUrl(generics.RetrieveAPIView):
    queryset = HTMLDocument.objects.all()
    serializer_class = HTMLDocumentSerializer
    permission_classes = (permissions.IsAuthenticated,)
    # lookup_url_kwarg = "source_url"
    lookup_field = "source_url"

    def get_object(self):
        """
        Returns the object the view is displaying.

        You may want to override this if you need to provide non-standard
        queryset lookups.  Eg if objects are referenced using multiple
        keyword arguments in the url conf.
        """
        queryset = self.filter_queryset(self.get_queryset())

        # Perform the lookup filtering.
        lookup_url_kwarg = self.lookup_url_kwarg or self.lookup_field

        assert lookup_url_kwarg in self.kwargs, (
            "Expected view %s to be called with a URL keyword argument "
            'named "%s". Fix your URL conf, or set the `.lookup_field` '
            "attribute on the view correctly."
            % (self.__class__.__name__, lookup_url_kwarg)
        )

        filter_kwargs = {
            self.lookup_field: urllib.parse.unquote(self.kwargs[lookup_url_kwarg])
        }
        obj = get_object_or_404(queryset, **filter_kwargs)

        # May raise a permission denied
        self.check_object_permissions(self.request, obj)

        return obj


class HTMLTableViewSet(viewsets.ModelViewSet):
    queryset = HTMLTable.objects.all()
    serializer_class = HTMLTableSerializer
    permission_classes = (permissions.IsAuthenticated,)
    lookup_field = "uuid"


@api_view(["GET"])
def html_table_retrieve_source_url_xpath(request):
    data = {
        "source_document": request.data.get("source_document"),
        "xpath": request.data.get("xpath"),
    }
    for k, v in data.items():
        if v is None:
            return Response(
                {"Must not be null": [k]}, status=status.HTTP_400_BAD_REQUEST
            )

    try:
        html_table = HTMLTable.objects.get(**data)
    except HTMLTable.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
    if request.method == "GET":
        serializer = HTMLTableSerializer(html_table, many=False)
        return Response(serializer.data)


class ClassificationTaskViewSet(viewsets.ModelViewSet):
    queryset = ClassificationTask.objects.all()
    serializer_class = ClassificationTaskSerializer
    permission_classes = (permissions.IsAuthenticated,)
    lookup_field = "uuid"


class ClassificationTaskGroupViewSet(viewsets.ModelViewSet):
    queryset = ClassificationTaskGroup.objects.all()
    serializer_class = ClassificationTaskGroupSerializer
    permission_classes = (permissions.IsAuthenticated,)
    lookup_field = "uuid"


class ClassificatonTaskGroupRetrieveName(generics.RetrieveAPIView):
    queryset = ClassificationTaskGroup.objects.all()
    serializer_class = ClassificationTaskGroupSerializer
    permission_classes = (permissions.IsAuthenticated,)
    lookup_field = "name"

    def get_object(self):
        """
        Returns the object the view is displaying.

        You may want to override this if you need to provide non-standard
        queryset lookups.  Eg if objects are referenced using multiple
        keyword arguments in the url conf.
        """
        queryset = self.filter_queryset(self.get_queryset())

        # Perform the lookup filtering.
        lookup_url_kwarg = self.lookup_url_kwarg or self.lookup_field

        assert lookup_url_kwarg in self.kwargs, (
            "Expected view %s to be called with a URL keyword argument "
            'named "%s". Fix your URL conf, or set the `.lookup_field` '
            "attribute on the view correctly."
            % (self.__class__.__name__, lookup_url_kwarg)
        )

        filter_kwargs = {
            self.lookup_field: urllib.parse.unquote_plus(self.kwargs[lookup_url_kwarg])
        }
        obj = get_object_or_404(queryset, **filter_kwargs)

        # May raise a permission denied
        self.check_object_permissions(self.request, obj)

        return obj

tat/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

tat/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

tat/templates/tasks/classificationtask_annotate.html
{% extends "centered_hero_wide.html" %}
{% load bulma_tags %}
{% load static %}

{% block title %}Classify Table{% endblock %}

{% block inner %}
<h1 class="title is-1">Classify Table</h1>
<div class="box">
  <h2 class="mb-3">{{ name }} <span class="pl-3 has-text-grey-light">{{ table_class }}</span></h2>
  <div class="columns is-centered">
    <div class="column is-half">
      <form class="field-body" action="{{self_url}}" method="GET">
        {{ context_form | bulma }}
        <div class="field">
          <label class="label">&nbsp</label>
          <button type="submit" class="button">Set Context</button>
        </div>
      </form>
    </div>
  </div>
      {% autoescape off %}
      {{ html_fragment }}
      {% endautoescape %}
</div>
<form id="annotation-form" class="box" method="post">
  {% csrf_token %}
  <p class="mb-3">Use the number keys to quickly select an option and press the 'd' key to submit the form.</p>
  {{ form| bulma }}
  <button type="submit" class="button is-primary">Complete</button>
</form>

<p>
Source: <a href="{{ html_source }}">{{ html_source }}</a>
</p>
<p>
xpath: {{xpath}}
</p>

<script>
  document.getElementById("classification_target").scrollIntoView();
  document.addEventListener('keydown', function(e) {
      if (document.activeElement == document.getElementById("id_before") || document.activeElement == document.getElementById("id_after")) {
        return;
      }
      let index = Number.parseInt(e.key);
      if (isNaN(index)) {
          if (e.key == 'd') {
              // submit form
              document.getElementById('annotation-form').submit();
            } else {
                return;
              }
        } else {
            // Select radio button by number
            let radioButton = document.getElementById(`id_table_class_${index-1}`);
            if (radioButton === null) {
                return;
              }
            radioButton.checked = true;
            radioButton.scrollIntoView()
            return;
          }
    })
</script>
{% endblock inner %}

tat/templates/tasks/classificationtask_confirm_delete.html
{% extends "centered_hero.html" %}
{% load static %}

{% block title %}Confirm Delete Classification Task{% endblock %}

{% block inner %}
<h1 class="title is-1">Delete Classification Task</h1>
<form class="box" method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete {{ object.group.name }}: {{ object.name }}?</p>
  <button type="submit" class="button is-danger">Delete</button>
</form>
{% endblock inner %}

tat/templates/tasks/classificationtaskgroup_add_tasks.html
{% extends "centered_hero.html" %}
{% load bulma_tags %}

{% block title %}Create Classification Task Group{% endblock %}

{% block inner %}
<h1 class="title is-1">Create Classification Task Group</h1>
<form class="box" method="post" enctype='multipart/form-data'>
  {% csrf_token %}
  <p class="subtitle is-5 has-text-dark">
  {{ task_group.name }}
  </p>
  <p>
  Class options:
  {% for class_option in task_group.table_class_options %}
  <span class="tag">
    {{ class_option }}
  </span>
  {% endfor %}
  </p>
  {{ form|bulma }}
  {% if redirect_field_value %}
  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
  {% endif %}
  <div class="field has-text-centered">
    <button class="button is-primary" type="submit">Save</button>
  </div>
</form>
{% endblock inner %}

tat/templates/tasks/classificationtaskgroup_confirm_delete.html
{% extends "centered_hero.html" %}
{% load static %}

{% block title %}Confirm Delete Classification Task Group{% endblock %}

{% block inner %}
<h1 class="title is-1">Delete Classification Task Group</h1>
<form class="box" method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete {{ object.group.name }}: {{ object.name }}?</p>
  <button type="submit" class="button is-danger">Delete</button>
</form>
{% endblock inner %}

tat/templates/tasks/classificationtaskgroup_edit.html
{% extends "centered_hero.html" %}
{% load bulma_tags %}

{% block title %}Edit Classification Task Group{% endblock %}

{% block inner %}
<h1 class="title is-1">Edit Classification Task Group</h1>
<form class="box" method="post">
  {% csrf_token %}
  {{ form|bulma }}
  {% if redirect_field_value %}
  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
  {% endif %}
  <div class="field has-text-centered">
    <button class="button is-primary" type="submit">Save</button>
  </div>
</form>
{% endblock inner %}

tat/templates/tasks/classificationtaskgroup_form.html
{% extends "centered_hero.html" %}
{% load bulma_tags %}

{% block title %}Create Classification Task Group{% endblock %}

{% block inner %}
<h1 class="title is-1">Create Classification Task Group</h1>
<form class="box" method="post" enctype='multipart/form-data'>
  {% csrf_token %}
  {{ form|bulma }}
  {% if redirect_field_value %}
  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
  {% endif %}
  <div class="field has-text-centered">
    <button class="button is-primary" type="submit">Create</button>
  </div>
</form>
{% endblock inner %}

tat/templates/tasks/classificationtaskgroup_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Classification Tasks{% endblock %}

{% block content %}
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column">
        <h1 class="title is-1">
            Classification Tasks
        </h1>
        {% if object_list %}
        {% for taskgroup in object_list %}
        <div class="card squishable-card {% if not forloop.last %} mb-4 {% endif %}">
          <div class="card-header">
            <p class="card-header-title is-centered">{{ taskgroup.name }} <span class="has-text-grey-light pl-2">[{{taskgroup.completed_task_count}}/{{taskgroup.tasks.count}}]</span></p>
          </div>
          <div class="card-content has-background-light is-squished">
            <div class="box">
              Class Options:
              {% for class_option in taskgroup.table_class_options %}
              <span class="tag">
                {{ class_option }}
              </span>
              {% endfor %}
            </div>
            <!-- Classification Task list-->
            {% for task in taskgroup.tasks.all %}
            <div class="card {% if not forloop.last %} mb-4 {% endif %}">
              <div class="card-header {% if task.completed %} has-background-success-light {% endif %}">
                <p class="card-header-title is-centered">
                  <a href="{% url 'tasks:classification_task_annotate' task.pk %}">
                    {{ task.name }}
                  </a>
                </p>
              </div>
                {% if request.user.type == "ADMIN" and task.completed %}
                <div class="card-content">
                  <p>completed by {{ task.completed_by.username }} at {{ task.completed_at }}</p>
                </div>
                {% endif %}
              {% if request.user.type == "ADMIN" %}
              <footer class="card-footer">
                <a href="{% url 'tasks:classification_task_delete' task.pk%}" class="card-footer-item">Delete</a>
              </footer>
              {% endif %}
            </div>
            {% endfor %}
          </div>
          {% if request.user.type == "ADMIN" %}
          <footer class="card-footer">
            <a href="{% url 'tasks:classification_group_edit' taskgroup.pk %}" class="card-footer-item">Edit</a>
            <a href="{% url 'tasks:classification_group_download' taskgroup.pk %}" class="card-footer-item" download>Download</a>
            <a href="{% url 'tasks:classification_group_delete' taskgroup.pk %}" class="card-footer-item">Delete</a>
          </footer>
          {% endif %}
        </div>
        {% endfor %}
        {% else %}
        <p class="subtitle is-3">There are no classification tasks</p>
        {% endif %}
      </div>
    </div>
  </div>
</section>

    <script>
      squishables = document.getElementsByClassName("squishable-card")
      Array.prototype.forEach.call(squishables, function(el, i){
        el.querySelector(".card-header").addEventListener('click', function () {
          console.log(this);
          if (this.parentElement.querySelector(".card-content").classList.contains("is-squished")) {
            this.parentElement.querySelector(".card-content").classList.remove("is-squished");
          } else {
            this.parentElement.querySelector(".card-content").classList.add("is-squished");
          }
        }, false);
      });
    </script>
{% endblock content %}

tat/templates/tasks/html_table_context.html
{% extends "centered_hero_wide.html" %}
{% load static %}

{% block title %}HTML Table Context{% endblock %}

{% block inner %}
<h1 class="title is-1">HTML Table Context</h1>
<div class="box">
  {% autoescape off %}
  {{ html_fragment }}
  {% endautoescape %}
</div>
{% endblock inner %}

tat/templates/tasks/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}Task Types{% endblock %}

{% block content %}
<section class ="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <nav class="panel">
        <p class="panel-heading">Task Types</p>
        {% for task_type in task_types %}
        <a class="panel-block" href="{{task_type.url}}">{{task_type.name}}</a>
        {% endfor %}
        </nav>
      </div>
    </div>
  </div>
</section>
{% endblock content %}